version: '3'

services:
  api:
    container_name: api
    build:
      context: ./api
    networks:
      - uqam-net
    ports:
      - 7800:7800
    depends_on:
      - database
  front:
    container_name: front
    build:
      context: ./web
    ports:
      - 3000:3000
  database:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - uqam-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - uqam-net
    ports:
      - 8081:80


volumes:
  db-data:

networks:
  uqam-net: